**Types Of Recommender Systems**

-Content Based(use tags)-similarity of content

-Collaborative filtering-based on user interests

-Hybrid Filtering

Here We are using Content Based

In [1]:
import pandas as pd
import numpy as np

In [3]:
movies=pd.read_csv("tmdb_5000_movies.csv")
credits=pd.read_csv("tmdb_5000_credits.csv")

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [8]:
credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [10]:
movies=movies.merge(credits,on="title")

In [11]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [ ]:
#we need to create tags so let's first identify which columns can be useful in creating tags
#genres
#id
#keywords
#title
#overview
#cast
#crew

In [ ]:
#original language not necessary as here most of the movies is in english

In [12]:
movies=movies[["movie_id","title","overview","genres","keywords","cast","crew"]]

In [13]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [16]:
movies.dropna(inplace=True)

In [17]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [19]:
movies.duplicated().sum()

0

In [25]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [23]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#have to convert the above type into
# ["Action","Adventre","Fantasy","Scifi"]

In [26]:
type(movies.iloc[0].genres)

str

In [31]:
#the values of genres are string of list of dictionaries
# so we have a special module named ast
import ast
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i["name"])
    return l

In [33]:
movies["genres"]=movies["genres"].apply(convert)

In [34]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [49]:
movies["keywords"]=movies["keywords"].apply(convert)

In [50]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [55]:
#from cast column we need only top 3 cast hence
def convert3(obj):
    l=[]
    counter =0
    for i in ast.literal_eval(obj):
        if counter !=3:
            l.append(i["name"])
            counter+=1
        else:
            break
    return l

In [57]:
movies["cast"]=movies["cast"].apply(convert3)

In [58]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [61]:
#we want only director's dictionary to extract..that is we want dictionary with job:director
movies["crew"][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [63]:
def fetch_director(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i["job"]=="Director":
            l.append(i["name"])
            break
    return l

In [65]:
movies["crew"]=movies["crew"].apply(fetch_director)

In [66]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [68]:
type(movies["overview"][0])

str

In [70]:
movies["overview"]=movies["overview"].apply(lambda x:x.split())

In [73]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [75]:
#Sam Worthington needed to be converted into SamWorthington...if keep same as previous they become two different tags that is sam one tag and worthinton one tag
#but in data we have another name Sam Mendes  so the reocmmendation become wrong

movies["genres"]=movies["genres"].apply(lambda x:[i.replace(" ","") for i in x])

In [76]:
movies["keywords"]=movies["keywords"].apply(lambda x:[i.replace(" ","") for i in x])
movies["cast"]=movies["cast"].apply(lambda x:[i.replace(" ","") for i in x])
movies["crew"]=movies["crew"].apply(lambda x:[i.replace(" ","") for i in x])

In [77]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [78]:
#now create tags columns
movies["tags"]=movies["overview"]+movies["genres"]+movies["keywords"]+movies["cast"]+movies["crew"]

In [80]:
new_df=movies[["movie_id","title","tags"]]

In [81]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [83]:
new_df["tags"]=new_df["tags"].apply(lambda x:" ".join(x))

C:\Users\HP\AppData\Local\Temp\ipykernel_16108\1804341217.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(lambda x:" ".join(x))

In [84]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [122]:
#we have an issues here is the words may contain like "action","actions","love","loving","loved" then if we use stemming it becomes ["love","love","love"]
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [123]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [124]:
new_df["tags"]=new_df["tags"].apply(stem)

C:\Users\HP\AppData\Local\Temp\ipykernel_16108\1027202188.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(stem)

In [125]:
new_df["tags"][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [126]:
new_df["tags"]=new_df["tags"].apply(lambda x:x.lower())

C:\Users\HP\AppData\Local\Temp\ipykernel_16108\4024514323.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(lambda x:x.lower())

In [127]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [128]:
#we have to find the similarity of two movies based on tags of two movies->calculate number of similar words in two tags
#convert tags into vector
#now each movie can become one vector
#the closest vector can be recommended
#text can be converted to vector there are many techiques like bag of vectors
#combine all tags and take 5k most common words and count how many times they appeared in each movie so that it forms a table....i.e in rows it contains movies
#tags and columns contains 5k most common words and values tells how many times they appeared and now the row of one movie is vector for that movie and 
#find 5 closest vectors
#we can't consider stop words->the are for is in a
# we use countvectorizer class
new_df["tags"][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [129]:
new_df["tags"][1]

"captain barbossa, long believ to be dead, ha come back to life and is head to the edg of the earth with will turner and elizabeth swann. but noth is quit as it seems. adventur fantasi action ocean drugabu exoticisland eastindiatradingcompani loveofone'slif traitor shipwreck strongwoman ship allianc calypso afterlif fighter pirat swashbuckl aftercreditsst johnnydepp orlandobloom keiraknightley goreverbinski"

In [130]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words="english")

In [131]:
# actually it gives cv.fit_transform(new_df["tags"]) a sparse vector so we have to convert it into an array
#each vector is a movie
vectors=cv.fit_transform(new_df["tags"]).toarray()

In [132]:
cv.fit_transform(new_df["tags"]).toarray().shape

(4806, 5000)

In [133]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [134]:
cv.get_feature_names_out()#the 5000 words

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [135]:
len(cv.get_feature_names_out())

5000

In [136]:
cv.get_feature_names_out()[450:]

array(['beer', 'befor', 'befriend', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [137]:
#we have calculate the distance between the vectors we can't calculate euclidian we usine cosine ..
#cosine similarity
from sklearn.metrics.pairwise import cosine_similarity

In [140]:
similarity=cosine_similarity(vectors)

In [139]:
cosine_similarity(vectors).shape

(4806, 4806)

In [141]:
similarity

array([[1.        , 0.08458258, 0.08718573, ..., 0.04559608, 0.        ,
        0.        ],
       [0.08458258, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.08718573, 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04559608, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [143]:
similarity[0]#it has distance from 1st movie to all other movies,,,,1st value is 1 as the relationship between itself is 1

array([1.        , 0.08458258, 0.08718573, ..., 0.04559608, 0.        ,
       0.        ])

In [146]:
new_df[new_df["title"]=="Avatar"].index[0]#needed to find index of a movie

0

In [150]:
#we want indexes of movies which are closer to the given movie,so we sort them and get first 5 but in sorting process we lose index so to keep index fxed we use enumaret
list(enumerate(similarity[0]))

[(0, 0.9999999999999998),
 (1, 0.08458258116519013),
 (2, 0.08718572905786445),
 (3, 0.074458079104994),
 (4, 0.19184045508446734),
 (5, 0.1098436937909367),
 (6, 0.04047223292581764),
 (7, 0.1487044791289829),
 (8, 0.06003002251876642),
 (9, 0.09802861627917438),
 (10, 0.10397504898200727),
 (11, 0.09592022754223367),
 (12, 0.09004503377814962),
 (13, 0.04559607525875532),
 (14, 0.12996881122750908),
 (15, 0.06367145399670132),
 (16, 0.08000711205939975),
 (17, 0.14165281524036175),
 (18, 0.09620723036050562),
 (19, 0.08489527199560176),
 (20, 0.05881716976750462),
 (21, 0.11115400287534567),
 (22, 0.0685591170191061),
 (23, 0.08718572905786445),
 (24, 0.05405405405405406),
 (25, 0.03465834966066909),
 (26, 0.1559625734730109),
 (27, 0.18944220058835154),
 (28, 0.11624763874381927),
 (29, 0.06590621627456203),
 (30, 0.06774581282657174),
 (31, 0.16120647005479025),
 (32, 0.0863465783552691),
 (33, 0.09863939238321438),
 (34, 0.0),
 (35, 0.10067340828210367),
 (36, 0.17348855898381338),
 (37, 0.08000711205939975),
 (38, 0.08219949365267865),
 (39, 0.08336550215650926),
 (40, 0.07798128673650545),
 (41, 0.1678603981989089),
 (42, 0.0),
 (43, 0.09208185110322616),
 (44, 0.03427955850955305),
 (45, 0.08284930213349333),
 (46, 0.14097096860865022),
 (47, 0.199363055707225),
 (48, 0.08561170049453902),
 (49, 0.059053859535749265),
 (50, 0.1144727614064285),
 (51, 0.0803381317273391),
 (52, 0.1487044791289829),
 (53, 0.04355035563093422),
 (54, 0.03163859985841663),
 (55, 0.0713262951621492),
 (56, 0.14019992744655632),
 (57, 0.024507154069793594),
 (58, 0.06839411288813299),
 (59, 0.07398532461669939),
 (60, 0.0186145197762485),
 (61, 0.23490461932490855),
 (62, 0.08489527199560176),
 (63, 0.08284930213349333),
 (64, 0.03001501125938321),
 (65, 0.01979131233319198),
 (66, 0.02279803762937766),
 (67, 0.16673100431301852),
 (68, 0.1221125021745327),
 (69, 0.026936179620310644),
 (70, 0.07702442489446452),
 (71, 0.07435223956449145),
 (72, 0.13699915608779772),
 (73, 0.03355780276070122),
 (74, 0.20518233866439894),
 (75, 0.10529962529853128),
 (76, 0.07271792483455794),
 (77, 0.014588051152682587),
 (78, 0.05134961659630968),
 (79, 0.06263607679944924),
 (80, 0.05114214254947678),
 (81, 0.11168711865749101),
 (82, 0.07702442489446452),
 (83, 0.18065550087085797),
 (84, 0.12527215359889848),
 (85, 0.11565903932254226),
 (86, 0.07194017065667525),
 (87, 0.11277677488692017),
 (88, 0.09158437663089954),
 (89, 0.058352204610730346),
 (90, 0.06213697660012),
 (91, 0.16916516233038026),
 (92, 0.06367145399670132),
 (93, 0.07194017065667525),
 (94, 0.1898315991504998),
 (95, 0.14237369936287486),
 (96, 0.07798128673650545),
 (97, 0.07045670884515312),
 (98, 0.07702442489446452),
 (99, 0.02702702702702703),
 (100, 0.07009996372327816),
 (101, 0.07798128673650545),
 (102, 0.12629480039223434),
 (103, 0.0803381317273391),
 (104, 0.056388387443460086),
 (105, 0.10514994558491725),
 (106, 0.06314740019611717),
 (107, 0.06263607679944924),
 (108, 0.14704292441876157),
 (109, 0.06575959492214292),
 (110, 0.04559607525875532),
 (111, 0.1522038868295523),
 (112, 0.07798128673650545),
 (113, 0.04393747751637468),
 (114, 0.04649905549752771),
 (115, 0.04433510985214727),
 (116, 0.048478616556371965),
 (117, 0.06003002251876642),
 (118, 0.03427955850955305),
 (119, 0.04393747751637468),
 (120, 0.0),
 (121, 0.11624763874381927),
 (122, 0.11810771907149853),
 (123, 0.11290968804428622),
 (124, 0.06839411288813299),
 (125, 0.07726033486461518),
 (126, 0.13513513513513514),
 (127, 0.14797064923339878),
 (128, 0.0),
 (129, 0.09394227846020416),
 (130, 0.027399831217559546),
 (131, 0.106676149412533),
 (132, 0.04559607525875532),
 (133, 0.028618190351607124),
 (134, 0.13151918984428584),
 (135, 0.0),
 (136, 0.023728949893812478),
 (137, 0.030528125543633176),
 (138, 0.12996881122750908),
 (139, 0.12141669877745292),
 (140, 0.04559607525875532),
 (141, 0.0885807893036239),
 (142, 0.08718572905786445),
 (143, 0.08787495503274936),
 (144, 0.050734628943184104),
 (145, 0.019510570275964215),
 (146, 0.01643989873053573),
 (147, 0.056388387443460086),
 (148, 0.09863939238321438),
 (149, 0.15719549837837185),
 (150, 0.16646698038757363),
 (151, 0.2056773510573183),
 (152, 0.08458258116519013),
 (153, 0.07974522228289),
 (154, 0.06213697660012),
 (155, 0.020712325533373332),
 (156, 0.059808916712167495),
 (157, 0.10067340828210367),
 (158, 0.13549162565314346),
 (159, 0.0644825880219161),
 (160, 0.11869522585912262),
 (161, 0.03224129401095805),
 (162, 0.03355780276070122),
 (163, 0.05134961659630968),
 (164, 0.08108108108108109),
 (165, 0.04649905549752771),
 (166, 0.12683657235796025),
 (167, 0.09158437663089954),
 (168, 0.17757120130114434),
 (169, 0.08948747402853657),
 (170, 0.10793322294408637),
 (171, 0.02302046277580654),
 (172, 0.21524880100025257),
 (173, 0.02348556961505104),
 (174, 0.07897471897389846),
 (175, 0.07194017065667525),
 (176, 0.029526929767874632),
 (177, 0.0),
 (178, 0.024784079854830485),
 (179, 0.07352146220938077),
 (180, 0.022371868507134143),
 (181, 0.04559607525875532),
 (182, 0.1186447494690624),
 (183, 0.0713262951621492),
 (184, 0.17757120130114434),
 (185, 0.05134961659630968),
 (186, 0.059808916712167495),
 (187, 0.1559625734730109),
 (188, 0.022371868507134143),
 (189, 0.1162476387438193),
 (190, 0.08561170049453902),
 (191, 0.04956815970966097),
 (192, 0.047457899787624956),
 (193, 0.07983920607777244),
 (194, 0.0),
 (195, 0.06003002251876642),
 (196, 0.05264981264926564),
 (197, 0.037470006725398436),
 (198, 0.058123819371909635),
 (199, 0.08867021970429453),
 (200, 0.11028219331407116),
 (201, 0.0),
 (202, 0.03163859985841663),
 (203, 0.08458258116519013),
 (204, 0.050141221056390024),
 (205, 0.07543142864047142),
 (206, 0.11241002017619531),
 (207, 0.07798128673650545),
 (208, 0.12427395320024),
 (209, 0.0685591170191061),
 (210, 0.07610194341477616),
 (211, 0.024784079854830485),
 (212, 0.0665026647782209),
 (213, 0.059808916712167495),
 (214, 0.0),
 (215, 0.06711560552140243),
 (216, 0.06575959492214292),
 (217, 0.0863465783552691),
 (218, 0.03874921291460643),
 (219, 0.09320546490018),
 (220, 0.18009006755629928),
 (221, 0.047960113771116836),
 (222, 0.08094446585163528),
 (223, 0.10529962529853128),
 (224, 0.06117355427146393),
 (225, 0.047457899787624956),
 (226, 0.030528125543633176),
 (227, 0.08336550215650926),
 (228, 0.11185934253567072),
 (229, 0.10892898631973956),
 (230, 0.0930725988812425),
 (231, 0.0),
 (232, 0.11277677488692017),
 (233, 0.10514994558491725),
 (234, 0.08710071126186844),
 (235, 0.07702442489446452),
 (236, 0.11277677488692017),
 (237, 0.06711560552140244),
 (238, 0.11241002017619531),
 (239, 0.09248165577087425),
 (240, 0.047960113771116836),
 (241, 0.08000711205939975),
 (242, 0.08219949365267865),
 (243, 0.09394227846020416),
 (244, 0.09320546490018),
 (245, 0.08219949365267865),
 (246, 0.07696578428840449),
 (247, 0.0),
 (248, 0.04559607525875532),
 (249, 0.14019992744655632),
 (250, 0.0),
 (251, 0.04244763599780088),
 (252, 0.02054987341316966),
 (253, 0.06367145399670132),
 (254, 0.07045670884515312),
 (255, 0.0),
 (256, 0.11314714296070713),
 (257, 0.05405405405405406),
 (258, 0.01793740008335438),
 (259, 0.06213697660012),
 (260, 0.20668850837512243),
 (261, 0.024507154069793594),
 (262, 0.10793322294408637),
 (263, 0.09863939238321438),
 (264, 0.0),
 (265, 0.027788500718836418),
 (266, 0.10028244211278005),
 (267, 0.06711560552140244),
 (268, 0.0533380747062665),
 (269, 0.03001501125938321),
 (270, 0.08948747402853657),
 (271, 0.07271792483455794),
 (272, 0.028194193721730043),
 (273, 0.021402925123634755),
 (274, 0.09097816785925636),
 (275, 0.1453095484297741),
 (276, 0.06327719971683327),
 (277, 0.05381220025006314),
 (278, 0.1186447494690624),
 (279, 0.07118684968143743),
 (280, 0.0),
 (281, 0.06590621627456203),
 (282, 0.02279803762937766),
 (283, 0.027788500718836418),
 (284, 0.0186145197762485),
 (285, 0.01979131233319198),
 (286, 0.07859774918918593),
 (287, 0.02632490632463282),
 (288, 0.027788500718836418),
 (289, 0.04649905549752771),
 (290, 0.06327719971683327),
 (291, 0.050141221056390024),
 (292, 0.09004503377814962),
 (293, 0.03001501125938321),
 (294, 0.1453095484297741),
 (295, 0.106676149412533),
 (296, 0.03929887459459296),
 (297, 0.04474373701426829),
 (298, 0.0),
 (299, 0.06025359879550432),
 (300, 0.17348855898381338),
 (301, 0.09491579957524988),
 (302, 0.07045670884515312),
 (303, 0.028194193721730043),
 (304, 0.06667259338283313),
 (305, 0.1926263261127128),
 (306, 0.08219949365267865),
 (307, 0.11022596991336672),
 (308, 0.0685591170191061),
 (309, 0.06327719971683327),
 (310, 0.03106848830006),
 (311, 0.1522038868295523),
 (312, 0.10146925788636821),
 (313, 0.055577001437672836),
 (314, 0.0),
 (315, 0.08458258116519013),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.10067340828210367),
 (320, 0.03106848830006),
 (321, 0.0),
 (322, 0.213352298825066),
 (323, 0.03001501125938321),
 (324, 0.024507154069793594),
 (325, 0.09672388203287416),
 (326, 0.05723638070321425),
 (327, 0.027399831217559546),
 (328, 0.027399831217559546),
 (329, 0.08000711205939975),
 (330, 0.10146925788636821),
 (331, 0.09119215051751065),
 (332, 0.10810810810810811),
 (333, 0.024784079854830485),
 (334, 0.09802861627917438),
 (335, 0.04697113923010208),
 (336, 0.07009996372327816),
 (337, 0.04604092555161308),
 (338, 0.0),
 (339, 0.04956815970966097),
 (340, 0.050141221056390024),
 (341, 0.08336550215650926),
 (342, 0.1633934794796094),
 (343, 0.019510570275964215),
 (344, 0.03001501125938321),
 (345, 0.023249527748763855),
 (346, 0.0),
 (347, 0.0),
 (348, 0.06213697660012),
 (349, 0.07610194341477616),
 (350, 0.04956815970966097),
 (351, 0.0),
 (352, 0.027788500718836418),
 (353, 0.041757384532966166),
 (354, 0.02196873875818734),
 (355, 0.036992662308349696),
 (356, 0.09158437663089952),
 (357, 0.0),
 (358, 0.06105625108726635),
 (359, 0.03163859985841663),
 (360, 0.02122381799890044),
 (361, 0.07610194341477616),
 (362, 0.09672388203287416),
 (363, 0.10042266465917388),
 (364, 0.023728949893812478),
 (365, 0.07610194341477616),
 (366, 0.05723638070321425),
 (367, 0.0),
 (368, 0.13151918984428584),
 (369, 0.1283740414907742),
 (370, 0.05134961659630968),
 (371, 0.09695723311274393),
 (372, 0.047960113771116836),
 (373, 0.1752499093081954),
 (374, 0.038482892144202245),
 (375, 0.06213697660011999),
 (376, 0.047457899787624956),
 (377, 0.0),
 (378, 0.0),
 (379, 0.05141933776432957),
 (380, 0.05264981264926564),
 (381, 0.08489527199560176),
 (382, 0.0),
 (383, 0.04433510985214727),
 (384, 0.029061909685954818),
 (385, 0.0),
 (386, 0.022167554926073633),
 (387, 0.023980056885558418),
 (388, 0.0),
 (389, 0.0885807893036239),
 (390, 0.02666903735313325),
 (391, 0.05733298225836872),
 (392, 0.030528125543633176),
 (393, 0.0),
 (394, 0.025070610528195012),
 (395, 0.05264981264926564),
 (396, 0.04433510985214727),
 (397, 0.05264981264926564),
 (398, 0.0),
 (399, 0.023980056885558418),
 (400, 0.09158437663089952),
 (401, 0.03106848830006),
 (402, 0.07897471897389846),
 (403, 0.08419653359482289),
 (404, 0.058123819371909635),
 (405, 0.056388387443460086),
 (406, 0.021049133398705722),
 (407, 0.021586644588817275),
 (408, 0.03287979746107146),
 (409, 0.0),
 (410, 0.09913631941932194),
 (411, 0.0533380747062665),
 (412, 0.09695723311274393),
 (413, 0.1389425035941821),
 (414, 0.03001501125938321),
 (415, 0.05381220025006314),
 (416, 0.05134961659630968),
 (417, 0.03287979746107146),
 (418, 0.03587480016670876),
 (419, 0.06974858324629157),
 (420, 0.1139901881468883),
 (421, 0.02348556961505104),
 (422, 0.11810771907149853),
 (423, 0.041757384532966166),
 (424, 0.037470006725398436),
 (425, 0.06475993376645182),
 (426, 0.05446449315986979),
 (427, 0.02702702702702703),
 (428, 0.056573571480353566),
 (429, 0.0),
 (430, 0.05134961659630968),
 (431, 0.024507154069793594),
 (432, 0.11624763874381928),
 (433, 0.03163859985841663),
 (434, 0.0),
 (435, 0.03587480016670876),
 (436, 0.0),
 (437, 0.02632490632463282),
 (438, 0.12392039927415242),
 (439, 0.02666903735313325),
 (440, 0.025070610528195012),
 (441, 0.058123819371909635),
 (442, 0.04604092555161308),
 (443, 0.06475993376645182),
 (444, 0.0),
 (445, 0.10028244211278005),
 (446, 0.02348556961505104),
 (447, 0.06532553344640132),
 (448, 0.021586644588817275),
 (449, 0.11115400287534567),
 (450, 0.021586644588817275),
 (451, 0.025367314471592052),
 (452, 0.03106848830006),
 (453, 0.024784079854830485),
 (454, 0.11742784807525519),
 (455, 0.061649620239508984),
 (456, 0.04393747751637468),
 (457, 0.08718572905786445),
 (458, 0.04393747751637468),
 (459, 0.03504998186163908),
 (460, 0.024507154069793594),
 (461, 0.14309095175803563),
 (462, 0.03271662128033808),
 (463, 0.03287979746107146),
 (464, 0.0),
 (465, 0.0),
 (466, 0.14704292441876154),
 (467, 0.10701462561817378),
 (468, 0.028194193721730043),
 (469, 0.06025359879550432),
 (470, 0.04604092555161308),
 (471, 0.06475993376645182),
 (472, 0.10959932487023819),
 (473, 0.09394227846020416),
 (474, 0.0),
 (475, 0.04433510985214727),
 (476, 0.1371182340382122),
 (477, 0.0),
 (478, 0.05479966243511909),
 (479, 0.0891578689526865),
 (480, 0.09913631941932194),
 (481, 0.0),
 (482, 0.022167554926073633),
 (483, 0.12655439943366653),
 (484, 0.029526929767874632),
 (485, 0.0533380747062665),
 (486, 0.08099356774626426),
 (487, 0.1289651760438322),
 (488, 0.06746792083200746),
 (489, 0.0),
 (490, 0.14349920066683505),
 (491, 0.1011805823145441),
 (492, 0.07702442489446452),
 (493, 0.03106848830006),
 (494, 0.0),
 (495, 0.19344776406574832),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0685591170191061),
 (499, 0.0),
 (500, 0.02632490632463282),
 (501, 0.08284930213349333),
 (502, 0.13549162565314346),
 (503, 0.07610194341477615),
 (504, 0.0),
 (505, 0.1371182340382122),
 (506, 0.03504998186163908),
 (507, 0.25903973506580724),
 (508, 0.10269923319261937),
 (509, 0.022371868507134143),
 (510, 0.10028244211278005),
 (511, 0.09320546490018),
 (512, 0.027788500718836418),
 (513, 0.1487044791289829),
 (514, 0.04956815970966097),
 (515, 0.025070610528195012),
 (516, 0.028618190351607124),
 (517, 0.0),
 (518, 0.04474373701426829),
 (519, 0.0),
 (520, 0.0),
 (521, 0.025367314471592052),
 (522, 0.024507154069793594),
 (523, 0.04901430813958719),
 (524, 0.0),
 (525, 0.047960113771116836),
 (526, 0.028618190351607124),
 (527, 0.03355780276070122),
 (528, 0.022581937608857246),
 (529, 0.1696751579473019),
 (530, 0.056388387443460086),
 (531, 0.04697113923010208),
 (532, 0.021586644588817275),
 (533, 0.06105625108726635),
 (534, 0.08489527199560176),
 (535, 0.09913631941932194),
 (536, 0.11399018814688831),
 (537, 0.0685591170191061),
 (538, 0.0),
 (539, 0.2537477434955704),
 (540, 0.07610194341477616),
 (541, 0.10701462561817376),
 (542, 0.037470006725398436),
 (543, 0.07194017065667525),
 (544, 0.056388387443460086),
 (545, 0.025070610528195012),
 (546, 0.0644825880219161),
 (547, 0.08336550215650926),
 (548, 0.0),
 (549, 0.12119654139092992),
 (550, 0.025070610528195012),
 (551, 0.03822198817224581),
 (552, 0.0),
 (553, 0.029061909685954818),
 (554, 0.0),
 (555, 0.04559607525875532),
 (556, 0.02702702702702703),
 (557, 0.12392039927415242),
 (558, 0.0),
 (559, 0.030528125543633176),
 (560, 0.03653310829007939),
 (561, 0.03224129401095805),
 (562, 0.03106848830006),
 (563, 0.025993762245501817),
 (564, 0.09004503377814962),
 (565, 0.04433510985214727),
 (566, 0.024239308278185982),
 (567, 0.025367314471592052),
 (568, 0.1430909517580356),
 (569, 0.047960113771116836),
 (570, 0.0685591170191061),
 (571, 0.04280585024726951),
 (572, 0.10887588907733554),
 (573, 0.021049133398705722),
 (574, 0.023728949893812478),
 (575, 0.04604092555161308),
 (576, 0.05264981264926564),
 (577, 0.20032733246124987),
 (578, 0.03796631983009995),
 (579, 0.14097096860865022),
 (580, 0.024507154069793594),
 (581, 0.14763464883937316),
 (582, 0.2484013136974297),
 (583, 0.03822198817224581),
 (584, 0.08219949365267865),
 (585, 0.024784079854830485),
 (586, 0.04559607525875532),
 (587, 0.07194017065667525),
 (588, 0.025993762245501817),
 (589, 0.1178966237837789),
 (590, 0.030528125543633176),
 (591, 0.06367145399670132),
 (592, 0.021402925123634755),
 (593, 0.0),
 (594, 0.050141221056390024),
 (595, 0.162746694241347),
 (596, 0.09394227846020416),
 (597, 0.06003002251876642),
 (598, 0.036760731104690386),
 (599, 0.027788500718836418),
 (600, 0.06906138832741962),
 (601, 0.033912921674035035),
 (602, 0.09208185110322616),
 (603, 0.05479966243511909),
 (604, 0.06711560552140244),
 (605, 0.02666903735313325),
 (606, 0.0),
 (607, 0.058531710827892644),
 (608, 0.0),
 (609, 0.047457899787624956),
 (610, 0.05881716976750462),
 (611, 0.023249527748763855),
 (612, 0.06420877537090426),
 (613, 0.036760731104690386),
 (614, 0.04956815970966097),
 (615, 0.06213697660012),
 (616, 0.03504998186163908),
 (617, 0.050734628943184104),
 (618, 0.08948747402853657),
 (619, 0.0),
 (620, 0.0),
 (621, 0.06575959492214292),
 (622, 0.021402925123634755),
 (623, 0.0),
 (624, 0.10283867552865913),
 (625, 0.03163859985841663),
 (626, 0.08336550215650926),
 (627, 0.11028219331407116),
 (628, 0.0),
 (629, 0.04901430813958719),
 (630, 0.024784079854830485),
 (631, 0.05134961659630968),
 (632, 0.07798128673650545),
 (633, 0.022581937608857246),
 (634, 0.07521183158458504),
 (635, 0.0665026647782209),
 (636, 0.023728949893812478),
 (637, 0.024507154069793594),
 (638, 0.03355780276070122),
 (639, 0.0),
 (640, 0.06070834938872646),
 (641, 0.0),
 (642, 0.0),
 (643, 0.10146925788636821),
 (644, 0.050734628943184104),
 (645, 0.04474373701426829),
 (646, 0.0533380747062665),
 (647, 0.04901430813958719),
 (648, 0.030528125543633176),
 (649, 0.0),
 (650, 0.05264981264926564),
 (651, 0.0),
 (652, 0.04355035563093422),
 (653, 0.10762440050012628),
 (654, 0.10524566699352861),
 (655, 0.024239308278185982),
 (656, 0.0),
 (657, 0.03504998186163908),
 (658, 0.04901430813958719),
 (659, 0.02567480829815484),
 (660, 0.0949157995752499),
 (661, 0.16839306718964578),
 (662, 0.0),
 (663, 0.0),
 (664, 0.06105625108726635),
 (665, 0.06906138832741962),
 (666, 0.050734628943184104),
 (667, 0.0),
 (668, 0.1371182340382122),
 (669, 0.03587480016670876),
 (670, 0.017727598712973542),
 (671, 0.06906138832741962),
 (672, 0.028618190351607124),
 (673, 0.02023611646290882),
 (674, 0.07194017065667525),
 (675, 0.04559607525875532),
 (676, 0.029061909685954818),
 (677, 0.025367314471592052),
 (678, 0.11624763874381927),
 (679, 0.0),
 (680, 0.07610194341477616),
 (681, 0.027788500718836418),
 (682, 0.02023611646290882),
 (683, 0.04901430813958719),
 (684, 0.0),
 (685, 0.03355780276070122),
 (686, 0.03224129401095805),
 (687, 0.10529962529853128),
 (688, 0.04393747751637468),
 (689, 0.0),
 (690, 0.025367314471592052),
 (691, 0.06003002251876642),
 (692, 0.11083777463036817),
 (693, 0.03427955850955305),
 (694, 0.022167554926073633),
 (695, 0.06711560552140244),
 (696, 0.021586644588817275),
 (697, 0.0),
 (698, 0.04393747751637468),
 (699, 0.03874921291460643),
 (700, 0.029061909685954818),
 (701, 0.058123819371909635),
 (702, 0.02279803762937766),
 (703, 0.021586644588817275),
 (704, 0.06906138832741962),
 (705, 0.024784079854830485),
 (706, 0.02196873875818734),
 (707, 0.0),
 (708, 0.025070610528195012),
 (709, 0.020878692266483083),
 (710, 0.058531710827892644),
 (711, 0.05264981264926564),
 (712, 0.0),
 (713, 0.025070610528195012),
 (714, 0.0),
 (715, 0.10067340828210367),
 (716, 0.027399831217559546),
 (717, 0.0),
 (718, 0.04559607525875532),
 (719, 0.0),
 (720, 0.02666903735313325),
 (721, 0.03287979746107146),
 (722, 0.0),
 (723, 0.025070610528195012),
 (724, 0.023980056885558418),
 (725, 0.0),
 (726, 0.0),
 (727, 0.03120812265889869),
 (728, 0.07352146220938079),
 (729, 0.04956815970966097),
 (730, 0.030660569226416797),
 (731, 0.05264981264926564),
 (732, 0.06839411288813299),
 (733, 0.06213697660011999),
 (734, 0.06774581282657174),
 (735, 0.06774581282657174),
 (736, 0.029061909685954818),
 (737, 0.07798128673650545),
 (738, 0.0),
 (739, 0.03874921291460643),
 (740, 0.1098436937909367),

In [152]:
#now sort
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]# now we get 5 closer movies along with indices

[(1214, 0.29061909685954823),
 (3728, 0.26401000024165),
 (507, 0.25903973506580724),
 (539, 0.2537477434955704),
 (2405, 0.2507061052819501)]

In [157]:
def recommend(movie):
    movie_index=new_df[new_df["title"]==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [158]:
recommend("Avatar")

Aliens vs Predator: Requiem
Falcon Rising
Independence Day
Titan A.E.
Aliens

In [156]:
new_df.iloc[1214].title

'Aliens vs Predator: Requiem'

In [161]:
import  pickle
pickle.dump(new_df,open("movie_list.pkl","wb"))

In [160]:
pickle.dump(similarity,open("similarity.pkl","wb"))